### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pjastrzabek** [goharbor/terraform-provider-harbor#229]
**Describe the bug**
Harbor provider occasionally crashes. Retry always works.
Harbor instance we operate on is deployed on Alicloud, while terraform client runs in Europe, thus we suspect network / timeout problems and bugs in error handling inside provider.

**To Reproduce**
Attempt to create robot account on harbor instance to which connection is not stable.

**Expected behavior**
Better errror message, maybe some internal retries in case of ConnectionError

**Stacktrace**
```
Error: Plugin did not respond
│ 
│   with harbor_robot_account.docker_pull_ali,
│   on harbor.tf line 163, in resource "harbor_robot_account" "docker_pull_ali":
│  163: resource "harbor_robot_account" "docker_pull_ali" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with harbor_robot_account.chart_pull_ali,
│   on harbor.tf line 248, in resource "harbor_robot_account" "chart_pull_ali":
│  248: resource "harbor_robot_account" "chart_pull_ali" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-harbor_v3.7.1 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x89c905]
goroutine 39 [running]:
github.com/BESTSELLER/terraform-provider-harbor/client.(*Client).SendRequest(0xc0003a0a40, {0xc04f78, 0x4}, {0xc073ff?, 0x6?}, {0xbd2d60, 0xc0005ac230}, 0xc9)
	github.com/BESTSELLER/terraform-provider-harbor/client/client.go:64 +0x545
github.com/BESTSELLER/terraform-provider-harbor/provider.resourceRobotAccountCreate(0x0?, {0xb7fba0?, 0xc0003a0a40})
	github.com/BESTSELLER/terraform-provider-harbor/provider/resource_robot_account.go:118 +0xff
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd254c0?, {0xd254c0?, 0xc0003c99e0?}, 0xd?, {0xb7fba0?, 0xc0003a0a40?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001ff260, {0xd254c0, 0xc0003c99e0}, 0xc0003c5450, 0xc000135b80, {0xb7fba0, 0xc0003a0a40})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002c6438, {0xd25418?, 0xc000555140?}, 0xc0003a9770)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002e0c80, {0xd254c0?, 0xc0003c9380?}, 0xc0005ac000)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbdade0?, 0xc0002e0c80}, {0xd254c0, 0xc0003c9380}, 0xc000566300, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032e8c0, {0xd27f50, 0xc0004e8680}, 0xc0000aa480, 0xc0004d23f0, 0x1192560, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc00032e8c0, {0xd27f50, 0xc0004e8680}, 0xc0000aa480, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.0/server.go:920 +0x28a
Error: The terraform-provider-harbor_v3.7.1 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by cedricmckinnie** [comment]
@Gaardsholt Hi, I would greatly appreciate if someone could help push this through. I think the merge failed due to a git sign-off requirement failure. Thanks!

**Comment by Gaardsholt** [comment]
@cedricmckinnie I am no longer part of this project, so no matter how much I would like to help, I cannot.
This project has been handed over to [goharbor](https://github.com/goharbor).

**Comment by gadamowicz** [comment]
I've found that the error is surfacing itself when provider can't access Harbor. Maybe this will help?
I'm facing this issue and managed to solve it by setting Harbor URL to localhost and forwarding ports via SSH.
