### ISSUE TITLE
Error Plugin did not respond

### ISSUE THREAD

**Issue by mamu-reply** [goharbor/terraform-provider-harbor#311]
**Describe the bug**
On Terraform i'm trying to apply an harbor configuration but the apply fails becouse some resources don't responds

**To Reproduce**
I've only created on Terraform this resource:
```
resource "harbor_user" "reader" {
  username  = var.harbor_reader_user_name
  password  = var.harbor_reader_user_password
  full_name = var.harbor_reader_user_name
  email     = var.harbor_reader_user_email
}
```

**Expected behavior**
That the terraform apply work correctly.

**Additional context**

```
│ Error: Plugin did not respond
│ 
│   with module.eks-cluster.module.harbor[0].harbor_user.reader,
│   on ../../modules/terraform-harbor/main-security.tf line 1, in resource "harbor_user" "reader":
│    1: resource "harbor_user" "reader" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.

│ Error: Plugin did not respond
│ 
│   with module.eks-cluster.module.harbor[0].harbor_registry.registries["trusted"],
│   on ../../modules/terraform-harbor/main.tf line 14, in resource "harbor_registry" "registries":
│   14: resource "harbor_registry" "registries" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.

│ Error: Plugin did not respond
│ 
│   with module.eks-cluster.module.harbor[0].harbor_registry.registries["proxy"],
│   on ../../modules/terraform-harbor/main.tf line 14, in resource "harbor_registry" "registries":
│   14: resource "harbor_registry" "registries" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-harbor_v3.7.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x89c905]

goroutine 49 [running]:
github.com/BESTSELLER/terraform-provider-harbor/client.(*Client).SendRequest(0xc000408700, {0xc04f78, 0x4}, {0xc0ab24?, 0xc00003f560?}, {0xbdcd60, 0xc000420b00}, 0xc9)
	github.com/BESTSELLER/terraform-provider-harbor/client/client.go:64 +0x545
github.com/BESTSELLER/terraform-provider-harbor/provider.resourceRegistryCreate(0x0?, {0xb7fba0?, 0xc000408700})
	github.com/BESTSELLER/terraform-provider-harbor/provider/resource_registry.go:70 +0x105
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd254c0?, {0xd254c0?, 0xc0000e17d0?}, 0xd?, {0xb7fba0?, 0xc000408700?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000260e00, {0xd254c0, 0xc0000e17d0}, 0xc000372a90, 0xc0001f0300, {0xb7fba0, 0xc000408700})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d1b8, {0xd25418?, 0xc0000dcc00?}, 0xc0004b1d60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000cc320, {0xd254c0?, 0xc0000e11d0?}, 0xc000492d20)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbdade0?, 0xc0000cc320}, {0xd254c0, 0xc0000e11d0}, 0xc000134a20, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000aa700, {0xd27f50, 0xc000254d00}, 0xc0001526c0, 0xc000342ba0, 0x1192560, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0000aa700, {0xd27f50, 0xc000254d00}, 0xc0001526c0, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

Error: The terraform-provider-harbor_v3.7.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

time=2023-03-31T11:08:05Z level=error msg=Terraform invocation failed in /home/vsts/work/1/s/namespaces/cedacri/customers/demo/sandboxes/demo-u-box-001/eu-central-1/eks-mupo/.terragrunt-cache/KdoTuUDQayfbWw3d1h2ykxGPp08/XOKcfp2SshCQ6bMV82g_EavC7k0/stacks/stack-aws-eks prefix=[/home/vsts/work/1/s/namespaces/cedacri/customers/demo/sandboxes/demo-u-box-001/eu-central-1/eks-mupo] 
time=2023-03-31T11:08:05Z level=error msg=1 error occurred:
	* exit status 1

```

- Provider Version 3.7.1
- Terraform Version 1.4.2
- Harbor Version 1.11.0 (Helm Chart)

**Comment by mamu-reply** [comment]
Hi @flbla! Thanks! with latest version this error not appear, but the resources are still not created perfectly, i have to relaunch the apply several times and it doesn't always create everything, for example i have this errors at first apply:
```
│ Error: [ERROR] unexpected status code got: 404 expected: 201 
│  404 page not found
│ 
│ 
│   with module.eks-cluster.module.harbor[0].harbor_config_auth.oidc[0],
│   on ../../modules/terraform-harbor/main-security.tf line 27, in resource "harbor_config_auth" "oidc":
│   27: resource "harbor_config_auth" "oidc" {
│ 
╵
╷
│ Error: [ERROR] unexpected status code got: 404 expected: 201 
│  404 page not found
│ 
│ 
│   with module.eks-cluster.module.harbor[0].harbor_registry.registries["trusted"],
│   on ../../modules/terraform-harbor/main.tf line 14, in resource "harbor_registry" "registries":
│   14: resource "harbor_registry" "registries" {
│ 
╵
╷
│ Error: [ERROR] unexpected status code got: 404 expected: 201 
│  404 page not found
│ 
│ 
│   with module.eks-cluster.module.harbor[0].harbor_registry.registries["proxy"],
│   on ../../modules/terraform-harbor/main.tf line 14, in resource "harbor_registry" "registries":
│   14: resource "harbor_registry" "registries" {
│ 
╵
```
and without changing anything i reapply and i get this:
```
╷
│ Error: [ERROR] unexpected status code got: 400 expected: 201 
│  {"errors":[{"code":"BAD_REQUEST","message":"the registry is unhealthy"}]}
│ 
│ 
│   with module.eks-cluster.module.harbor[0].harbor_registry.registries["trusted"],
│   on ../../modules/terraform-harbor/main.tf line 14, in resource "harbor_registry" "registries":
│   14: resource "harbor_registry" "registries" {
│ 
╵
╷
│ Error: [ERROR] unexpected status code got: 400 expected: 201 
│  {"errors":[{"code":"BAD_REQUEST","message":"the registry is unhealthy"}]}
│ 
│ 
│   with module.eks-cluster.module.harbor[0].harbor_registry.registries["proxy"],
│   on ../../modules/terraform-harbor/main.tf line 14, in resource "harbor_registry" "registries":
│   14: resource "harbor_registry" "registries" {
│ 
```
Do you know what it could be?

**Comment by flbla** [comment]
Hi,
do you still have the issue ?

│ Error: [ERROR] unexpected status code got: 400 expected: 201 
│  {"errors":[{"code":"BAD_REQUEST","message":"the registry is unhealthy"}]}

Does your Harbor was up and running ?

**Comment by mamu-reply** [comment]
> Hi, do you still have the issue ?
> 
> │ Error: [ERROR] unexpected status code got: 400 expected: 201 │ {"errors":[{"code":"BAD_REQUEST","message":"the registry is unhealthy"}]}
> 
> Does your Harbor was up and running ?

Hi, 
when I create it, it always gives me those errors, but it seems to work, even if without those configurations

**Comment by flbla** [comment]
do you use the default admin user ?

can you try to a `curl -X GET --user USER:PASSWORD https://HARBOR/api/v2.0/configurations` ?
